# Generated by Django 4.1.6 on 2023-03-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('context', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images')),
                ('on_public', models.BooleanField(default=True)),
                ('external_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '배너',
                'verbose_name_plural': '배너 목록',
            },
        ),
    ]
