# Generated by Django 4.1.6 on 2023-02-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.FloatField(default=0, max_length=5, verbose_name='assets'),
        ),
    ]
