# Generated by Django 4.1.6 on 2023-02-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='choices_list',
            field=models.ManyToManyField(related_name='votes_list', to='votes.choice'),
        ),
    ]
