# Generated by Django 4.1.6 on 2023-02-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_vote_choices_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='choices_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='votes_list', to='votes.choice'),
        ),
    ]
