# Generated by Django 4.1.6 on 2023-02-03 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_alter_vote_choices_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='choices_list',
        ),
    ]
