# Generated by Django 4.1.6 on 2023-02-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bankname', models.CharField(max_length=50)),
                ('bankcode', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
