# Generated by Django 4.1.6 on 2023-02-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
