# Generated by Django 4.1.6 on 2023-02-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_remove_feed_worklogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='poster',
        ),
    ]
