# Generated by Django 4.1.6 on 2023-02-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_remove_worklog_photos_remove_worklog_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='backgroundimage',
            field=models.ImageField(upload_to=''),
        ),
    ]
