# Generated by Django 4.1.6 on 2023-02-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_alter_feed_backgroundimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='on_public',
            field=models.BooleanField(default=False),
        ),
    ]
