# Generated by Django 4.1.6 on 2023-03-02 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ 관리', 'verbose_name_plural': 'FAQ 목록 관리'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': '공지사항 관리', 'verbose_name_plural': '공지사항 목록 관리'},
        ),
    ]
