# Generated by Django 4.1.6 on 2023-03-02 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': '음원 관리', 'verbose_name_plural': '음원 목록 관리'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': '이미지 관리', 'verbose_name_plural': '이미지 목록 관리'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '비디오 관리', 'verbose_name_plural': '비디오 목록 관리'},
        ),
    ]
