# Generated by Django 4.1.6 on 2023-02-08 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_alter_feed_backgroundimage'),
        ('medias', '0002_alter_music_file_alter_photo_file_alter_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='worklog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musics', to='feeds.feed'),
        ),
    ]
