# Generated by Django 4.1.6 on 2023-02-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('medias', '0003_alter_music_worklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='ganres',
            field=models.ManyToManyField(related_name='musics', to='genres.genre'),
        ),
    ]
