# Generated by Django 4.1.6 on 2023-03-15 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donates_from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donate',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donates_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
