# Generated by Django 4.1.6 on 2023-02-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
