# Generated by Django 4.1.6 on 2023-02-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_wallet_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='bisou',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('google_play_store', 'Google Play Store'), ('apple_store', 'apple store'), ('paypal', 'Paypal')], max_length=20, null=True),
        ),
    ]
